=== Viturico/project-pickamovie/src/data/pickamovie.dtd
<!ENTITY acc "Acción">
<!ENTITY com "Comedia">
<!ENTITY drm "Drama">
<!ENTITY ter "Terror">
<!ENTITY sfi "Ciencia Ficción">
<!ENTITY rom "Romance">
<!ENTITY ani "Animación">
<!ENTITY thr "Suspense">
<!ENTITY doc "Documental">
<!ENTITY mus "Musical">
<!ENTITY bel "Bélica">

<!ELEMENT movies (movie+)>
<!ELEMENT movie (title, year, director+, summary, actor+, script+, photo*, music*, genre+, duration, ytId, rating)>

<!ATTLIST movie poster CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT script (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT music (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT ytId (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

=== Viturico/project-pickamovie/src/data/pickamovie.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="pickamovie.xslt" type="text/xsl"?>
<!DOCTYPE movies SYSTEM "pickamovie.dtd">
<movies>
    <movie poster="https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg">
        <title>Blade Runner</title>
        <year>1982</year>
        <director>Ridley Scott</director>
        <summary>2019. Los Replicantes, robots casi humanos creados por la corporación Tyrell, han sido desterrados de la Tierra tras una rebelión. El ex Blade Runner Rick Deckard es llamado de nuevo al servicio para encontrar y "retirar" a un grupo de replicantes rebeldes.</summary>
        <actor>Harrison Ford</actor>
        <actor>Sean Young</actor>
        <actor>Rutger Hauer</actor>
        <script>David Webb Peoples</script>
        <script>Hampton Fancher</script>
        <photo>Jordan Cronenweth</photo>
        <music>Vangelis</music>
        <genre>&sfi;</genre>
        <genre>&acc;</genre>
        <duration>117</duration>
        <ytId>qoEyZoOTtss</ytId>
        <rating>8</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg">
        <title>Marty Supreme</title>
        <year>2025</year>
        <director>Josh Safdie</director>
        <summary>En los años 50, Marty Reisman, leyenda del tenis de mesa estadounidense, pasa de ser un estafador de apuestas en Manhattan a estrella internacional, acumulando 22 títulos en seis décadas.</summary>
        <actor>Timothée Chalamet</actor>
        <actor>Gwyneth Paltrow</actor>
        <actor>Tyler, the Creator</actor>
        <script>Josh Safdie</script>
        <script>Ronald Bronstein</script>
        <photo>Darius Khondji</photo>
        <music>TBC</music>
        <genre>&drm;</genre>
        <duration>120</duration>
        <ytId>s9gSuKaKcqM</ytId>
        <rating>8.0</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg">
        <title>Dune: Parte Dos</title>
        <year>2024</year>
        <director>Denis Villeneuve</director>
        <summary>Paul Atreides se une a los Fremen en un viaje de venganza contra quienes destruyeron a su familia. Mientras asciende como el profetizado Muad'Dib, debe equilibrar su amor por Chani con un destino que podría desatar una Guerra Santa a través del universo.</summary>
        <actor>Timothée Chalamet</actor>
        <actor>Zendaya</actor>
        <actor>Rebecca Ferguson</actor>
        <script>Denis Villeneuve</script>
        <script>Jon Spaihts</script>
        <photo>Greig Fraser</photo>
        <music>Hans Zimmer</music>
        <genre>&sfi;</genre>
        <genre>&acc;</genre>
        <duration>166</duration>
        <ytId>U2Qp5pL3ovA</ytId>
        <rating>8.0</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg">
        <title>Civil War</title>
        <year>2024</year>
        <director>Alex Garland</director>
        <summary>En un futuro distópico, Estados Unidos vive una Segunda Guerra Civil. Un equipo de periodistas emprende un peligroso viaje por carretera hacia Washington D.C. para documentar el conflicto antes de que las fuerzas rebeldes tomen la Casa Blanca.</summary>
        <actor>Kirsten Dunst</actor>
        <actor>Wagner Moura</actor>
        <script>Alex Garland</script>
        <photo>Rob Hardy</photo>
        <music>Ben Salisbury</music>
        <genre>&acc;</genre>
        <genre>&thr;</genre>
        <duration>109</duration>
        <ytId>aDyQxtg0V2w</ytId>
        <rating>7.0</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg">
        <title>El Padrino</title>
        <year>1972</year>
        <director>Francis Ford Coppola</director>
        <summary>Vito Corleone lidera una de las familias más poderosas del crimen organizado en Nueva York. Tras un intento de asesinato, su hijo Michael, que había intentado mantenerse al margen, se ve arrastrado al mundo de la mafia y comienza una transformación imparable.</summary>
        <actor>Marlon Brando</actor>
        <actor>Al Pacino</actor>
        <script>Mario Puzo</script>
        <script>Francis Ford Coppola</script>
        <photo>Gordon Willis</photo>
        <music>Nino Rota</music>
        <genre>&drm;</genre>
        <genre>&thr;</genre>
        <duration>175</duration>
        <ytId>sY1S34973zA</ytId>
        <rating>9.0</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg">
        <title>Pulp Fiction</title>
        <year>1994</year>
        <director>Quentin Tarantino</director>
        <summary>Las vidas de dos asesinos a sueldo, un boxeador, la esposa de un gángster y una pareja de atracadores se entrelazan en cuatro historias de violencia y redención en los bajos fondos de Los Ángeles, narradas con estructura temporal fracturada.</summary>
        <actor>John Travolta</actor>
        <actor>Samuel L. Jackson</actor>
        <actor>Uma Thurman</actor>
        <script>Quentin Tarantino</script>
        <photo>Andrzej Sekula</photo>
        <music>Varios</music>
        <genre>&thr;</genre>
        <genre>&acc;</genre>
        <duration>153</duration>
        <ytId>yMXB9u4z8Ic</ytId>
        <rating>8.5</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg">
        <title>El viaje de Chihiro</title>
        <year>2001</year>
        <director>Hayao Miyazaki</director>
        <summary>Chihiro, una niña de diez años, queda atrapada en un mundo de dioses y espíritus donde sus padres son convertidos en cerdos. Para salvarlos, deberá trabajar en una casa de baños termales bajo las órdenes de la bruja Yubaba y recuperar su nombre.</summary>
        <actor>Rumi Hiiragi</actor>
        <actor>Miyu Irino</actor>
        <script>Hayao Miyazaki</script>
        <photo>Atsushi Okui</photo>
        <music>Joe Hisaishi</music>
        <genre>&ani;</genre>
        <genre>&sfi;</genre>
        <duration>124</duration>
        <ytId>ByXuk9QqQkk</ytId>
        <rating>8.0</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg">
        <title>Parásitos</title>
        <year>2019</year>
        <director>Bong Joon-ho</director>
        <summary>La familia Kim, desempleada y paupérrima, se infiltra poco a poco en la mansión de la adinerada familia Park haciéndose pasar por profesionales independientes. Su estafa perfecta se desmorona cuando descubren un oscuro secreto escondido en la casa.</summary>
        <actor>Song Kang-ho</actor>
        <actor>Lee Sun-kyun</actor>
        <script>Bong Joon-ho</script>
        <photo>Hong Kyung-pyo</photo>
        <music>Jung Jae-il</music>
        <genre>&thr;</genre>
        <genre>&drm;</genre>
        <duration>132</duration>
        <ytId>5xH0HfJHsaY</ytId>
        <rating>9.5</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg">
        <title>La lista de Schindler</title>
        <year>1993</year>
        <director>Steven Spielberg</director>
        <summary>Oskar Schindler, empresario alemán y miembro del partido nazi, llega a Cracovia para hacer fortuna con mano de obra judía. Al presenciar los horrores del Holocausto, su conciencia despierta y arriesga su fortuna y su vida para salvar a más de mil judíos.</summary>
        <actor>Liam Neeson</actor>
        <actor>Ben Kingsley</actor>
        <script>Steven Zaillian</script>
        <photo>Janusz Kaminski</photo>
        <music>John Williams</music>
        <genre>&drm;</genre>
        <duration>195</duration>
        <ytId>gG22XNhtnoY</ytId>
        <rating>8.5</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg">
        <title>El Caballero Oscuro</title>
        <year>2008</year>
        <director>Christopher Nolan</director>
        <summary>La paz de Gotham se ve amenazada por el Joker, un criminal sádico cuyo objetivo es sumir la ciudad en la anarquía. Batman deberá tomar decisiones imposibles mientras el Joker empuja a Harvey Dent, el Caballero Blanco de Gotham, hacia la locura.</summary>
        <actor>Christian Bale</actor>
        <actor>Heath Ledger</actor>
        <script>Jonathan Nolan</script>
        <script>Christopher Nolan</script>
        <photo>Wally Pfister</photo>
        <music>Hans Zimmer</music>
        <genre>&acc;</genre>
        <genre>&thr;</genre>
        <duration>152</duration>
        <ytId>EXeTwQWrcwY</ytId>
        <rating>8.5</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg">
        <title>Cadena Perpetua</title>
        <year>1994</year>
        <director>Frank Darabont</director>
        <summary>Andy Dufresne, banquero condenado injustamente a cadena perpetua, utiliza su inteligencia para ganarse el favor de los guardias y el alcaide en la prisión de Shawshank. Mientras mantiene viva la esperanza, trama en secreto un plan para recuperar su libertad.</summary>
        <actor>Tim Robbins</actor>
        <actor>Morgan Freeman</actor>
        <script>Frank Darabont</script>
        <photo>Roger Deakins</photo>
        <music>Thomas Newman</music>
        <genre>&drm;</genre>
        <duration>142</duration>
        <ytId>6hB3S9bIaco</ytId>
        <rating>9.0</rating>
    </movie>
    <movie poster="https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg">
        <title>Psicosis</title>
        <year>1960</year>
        <director>Alfred Hitchcock</director>
        <summary>Marion Crane, una secretaria que huye tras robar 40.000 dólares, para la noche en el Motel Bates. Su misteriosa desaparición lleva a un detective y a su hermana a investigar, descubriendo la aterradora verdad que esconden Norman Bates y su madre.</summary>
        <actor>Anthony Perkins</actor>
        <actor>Janet Leigh</actor>
        <script>Joseph Stefano</script>
